Fix /jamute muting too many groups
DevotedMC/JukeAlert pull request #39
Opened 2017-07-07 05:20 UTC by iykHvfIvfR

Fixes https://github.com/DevotedMC/JukeAlert/issues/31

A workaround, might hurt performance, might not. A proper solution would require changing the way the /jamute group data is stored in the DB.

2017-07-08 04:50 UTC, ProgrammerDan commented
I'm not entirely sure I grok this yet, I'll have to look at the db a bit

2017-07-08 11:57 UTC, iykHvfIvfR commented
The way muted groups are stored in the db is as follows:

uuid | space-separated-groups
-|-
kjfdjf8dsjf8ds | test test123 testtest

The code checks which uuids ignore a particular group by checking if the group's name is anywhere in the space-separated-groups string:
 
- https://github.com/iykHvfIvfR/JukeAlert/blob/master/src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1626

```java
String sql = "%" + ignoredGroup + "%";
getIgnoreUUIDSStmt.setString(1, sql);
ResultSet set = getIgnoreUUIDSStmt.executeQuery();
```
- https://github.com/iykHvfIvfR/JukeAlert/blob/master/src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L592

```java
getIgnoreUUIDSStmt = db.prepareStatement(String.format(
    "SELECT * FROM %s WHERE muted_groups LIKE ? ;", mutedGroupsTbl));
```

So the root of the problem is that the muted groups are stored as a string instead of in a way that the db understands as a set of values.

My fix checks if the muted group actually exists in each `uuid: muted_groups` key pair received from the DB.

2017-07-08 13:47 UTC, ProgrammerDan commented
Oh wow, I'd forgotten how terrible that is. Ok, thanks for the explain!

2017-07-09 01:08 UTC, ProgrammerDan requested changes
Thought I published this hours ago, sorrry!

2017-07-09 01:08 UTC, ProgrammerDan commented on src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java
> +			Set<String> mutedGroupsSet = new HashSet<String>(Arrays.asList(mutedGroups));
Save a Set, use List instead.

Arrays.asList(mutedGroups) will return an object of interface type List<String> -- this also has "contains()".

As written right now, you're taking a lightweight array, iterating over it to make a List, then iterating over it again to make a set, so you can get log(n) performance on the contains().

Slight improvement to just use the Arrays.asList() result and use Contains on it, and uses less memory.

2017-07-09 04:14 UTC, iykHvfIvfR commented on src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java
> +			Set<String> mutedGroupsSet = new HashSet<String>(Arrays.asList(mutedGroups));
Ye I just wanted the O(1) on .contains(), probably irrelevant as there's only so many groups a player will have muted.

BTW, Arrays.asList() is O(1) and so is the .contains() on HashSet no?

2017-07-12 06:04 UTC, ProgrammerDan commented on src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java
> +			List<String> mutedGroupsSet = new ArrayList<String>(Arrays.asList(mutedGroups));
I probably wasn't clear.

Arrays.asList(mutedGroups) --- all by itself, don't wrap it with anything else.

2017-07-12 06:22 UTC, merged

2017-07-12 14:07 UTC, ProgrammerDan commented on src/main/java/com/untamedears/JukeAlert/storage/JukeAlertLogger.java
> +			Set<String> mutedGroupsSet = new HashSet<String>(Arrays.asList(mutedGroups));
Arrays.asList() appears to be O(1) yea.  new Set( _list_ ) is O(n) -- so at least in that original version you had O(1) + O(n) to get O(1) retrieval (best case). With streamlined, you just have O(1) to get O(n) retrieval, plus no hash computations during set setup, etc. ... largely pedantry at this scale, but always good to keep goal in mind. Spending O(n) for O(1) retrieval makes sense if you do it more then once. In this case where you're setting up a set just to throw it away after a single .contains() -- wouldn't make sense to do the hash setup.